# Generated by Django 4.1.7 on 2023-04-06 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0004_delete_category_alter_article_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='categroy',
            new_name='category',
        ),
    ]
