# Generated by Django 4.1.7 on 2023-04-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_post_completed_post_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dday',
            field=models.IntegerField(default=0),
        ),
    ]
